### ISSUE TITLE
can you include ExampleData in the repository?

### ISSUE THREAD

**Issue by AmazingAng** [MattNolanLab/grid_cell_analysis#3]
I tried to run example_spatial_analysis.py, but it requires ExampleData/spatial_firing.pkl and ExampleData/position.pkl.
Can you include ExampleData to the repository? or where I can find them?

**Comment by klaragerlei** [comment]
Thank you for the feedback, and sorry about this! I added the missing folder with the example data to the repo. 
The rest of the data is here: https://datashare.is.ed.ac.uk/handle/10283/3674

**Comment by AmazingAng** [comment]
> Thank you for the feedback, and sorry about this! I added the missing folder with the example data to the repo.
> The rest of the data is here: https://datashare.is.ed.ac.uk/handle/10283/3674

Thanks for your kindly reply. 
Yes, I looked at the website and tried to download a few pickles, like Basic information on data set (144.7Mb), but none of them have the structure like spatial_firing.pkl or position.pkl.

**Comment by klaragerlei** [comment]
'Sorted clusters' should have all the cells combined in one data frame

**Comment by AmazingAng** [comment]
I noticed that you update ExampleData. Many thanks!
